language: node_js

node_js:
  - "7"

addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
       - libgnome-keyring-dev
    packages:
      - g++-4.8
    packages:
      - xvfb

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev

before_script:
  - npm install -g bower gulp-cli mocha
  - npm run-script test-on-travis
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - gulp coverage_frontend
  - npm run-script test-on-travis

services: mysql
